services:
  postgres:
    container_name: psql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - /var/lib/data/postgresql

volumes:
  postgres: